name: Flugel Unit Tests
on: push
jobs:
  go-tests:
    name: Run Flugel Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Config Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.12.21
      - name: Download Go Modules
        working-directory: flugeltest
        run: go mod download
      - name: Run Go Tests
        working-directory: flugeltest
        run: go test -v -tags=unit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'franciscolbmota-branch1'
          AWS_ACCESS_KEY_ID:  ${{ secrets.Flugel_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.Flugel_ACCESS_KEY }}
